import { afterAll, describe, expect, test } from "bun:test";
import { createServer } from "node:net";
import { mkdtemp, readFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { Database } from "bun:sqlite";

const root=resolve(import.meta.dir,"..");
const configuredBinary=process.env.BLACKGLASS_RUST_BINARY;
const rustBinary=configuredBinary??join(root,"apps/server-rust/target/debug/blackglass-server");
const children:Array<ReturnType<typeof Bun.spawn>>=[];const sockets:WebSocket[]=[];
afterAll(async()=>{for(const socket of sockets)socket.close();for(const child of children)if(child.exitCode===null)child.kill("SIGTERM");await Promise.all(children.map(c=>c.exited));});

describe("Bun SQLite to Rust migration",()=>{
  test("reads legacy inline ciphertext and writes bounded external ciphertext",async()=>{
    const directory=await mkdtemp(join(tmpdir(),"obsidian-db-migration-"));const legacyDatabasePath=join(directory,"legacy.sqlite");const databasePath=join(directory,"server.sqlite");const [controlPort,dataPort]=await Promise.all([freePort(),freePort()]);
    const oracleToken="migration-oracle-token-long-enough-123";
    const oracle=Bun.spawn(["bun","run","apps/server/src/index.ts"],{cwd:root,stdout:"pipe",stderr:"pipe",env:{...process.env,SELFHOST_BIND_HOST:"127.0.0.1",SELFHOST_CONTROL_PORT:String(controlPort),SELFHOST_DATA_PORT:String(dataPort),SELFHOST_DATA_HOST:`127.0.0.1:${dataPort}`,SELFHOST_DATABASE:legacyDatabasePath,SELFHOST_EMAIL:"migration@example.test",SELFHOST_PASSWORD:"migration-password",SELFHOST_TOKEN:oracleToken,SELFHOST_NAME:"Migration owner",SELFHOST_PER_FILE_MAX:String(8*1024*1024)}});children.push(oracle);await health(controlPort,oracle);
    const vault=await post(controlPort,"/vault/create",{token:oracleToken,name:"Migrated vault",keyhash:"opaque-key",salt:"opaque-salt",region:"selfhost",encryption_version:3});
    const legacy=new TextEncoder().encode("legacy inline opaque ciphertext");const writer=await Probe.connect(`ws://127.0.0.1:${dataPort}`);await initialize(writer,oracleToken,vault,"Bun writer",0,true);writer.json(push("legacy-path","legacy-hash",legacy.length));expect(await writer.nextJson()).toEqual({res:"next"});writer.socket.send(legacy);const legacyNotice=await writer.nextJson();expect(await writer.nextJson()).toEqual({res:"ok"});writer.socket.close();
    oracle.kill("SIGTERM");await oracle.exited;

    const legacyBefore=await readFile(legacyDatabasePath);if(!configuredBinary){const build=Bun.spawnSync(["cargo","build","--manifest-path",join(root,"apps/server-rust/Cargo.toml")],{cwd:root,stdout:"pipe",stderr:"pipe"});expect(build.exitCode,build.stderr.toString()).toBe(0);}const migrate=Bun.spawnSync([rustBinary,"migrate-legacy",legacyDatabasePath,databasePath],{cwd:root,stdout:"pipe",stderr:"pipe"});expect(migrate.exitCode,migrate.stderr.toString()).toBe(0);expect(new Uint8Array(await readFile(legacyDatabasePath))).toEqual(new Uint8Array(legacyBefore));
    const rust=Bun.spawn([rustBinary,"serve"],{cwd:root,stdout:"pipe",stderr:"pipe",env:{...process.env,SELFHOST_BIND_HOST:"127.0.0.1",SELFHOST_CONTROL_PORT:String(controlPort),SELFHOST_DATA_PORT:String(dataPort),SELFHOST_DATA_HOST:`127.0.0.1:${dataPort}`,SELFHOST_DATABASE:databasePath,SELFHOST_STAGING_DIR:join(directory,"uploads"),SELFHOST_EMAIL:"migration@example.test",SELFHOST_PASSWORD:"migration-password",SELFHOST_ALLOW_PLAINTEXT_PASSWORD:"1",SELFHOST_NAME:"Migration owner",SELFHOST_PER_FILE_MAX:String(8*1024*1024),SELFHOST_ALLOWED_ORIGIN:"app://obsidian.md",SELFHOST_LOG_FORMAT:"pretty"}});children.push(rust);await health(controlPort,rust);
    const signin=await post(controlPort,"/user/signin",{email:"migration@example.test",password:"migration-password"});const reader=await Probe.connect(`ws://127.0.0.1:${dataPort}`);reader.json(init(signin.token,vault,"Rust reader",0,true));expect(await reader.nextJson()).toMatchObject({res:"ok"});expect(await reader.nextJson()).toMatchObject({op:"push",uid:legacyNotice.uid,path:"legacy-path"});expect(await reader.nextJson()).toEqual({op:"ready",version:legacyNotice.uid});reader.json({op:"pull",uid:legacyNotice.uid});expect(await reader.nextJson()).toMatchObject({res:"ok",size:legacy.length});expect(new Uint8Array(await reader.nextBinary())).toEqual(legacy);
    const modern=new TextEncoder().encode("new external opaque ciphertext");reader.json(push("modern-path","modern-hash",modern.length));expect(await reader.nextJson()).toEqual({res:"next"});reader.socket.send(modern);const modernNotice=await reader.nextJson();expect(await reader.nextJson()).toEqual({res:"ok"});reader.json({op:"pull",uid:modernNotice.uid});expect(await reader.nextJson()).toMatchObject({res:"ok",size:modern.length});expect(new Uint8Array(await reader.nextBinary())).toEqual(modern);
    const sqlite=new Database(databasePath,{readonly:true});const rows=sqlite.query("SELECT r.uid,r.content IS NOT NULL AS inline,rc.content IS NOT NULL AS external FROM revisions r LEFT JOIN revision_content rc ON rc.uid=r.uid ORDER BY r.uid").all() as Array<{uid:number;inline:number;external:number}>;const migrations=sqlite.query("SELECT version FROM schema_migrations ORDER BY version").all() as Array<{version:number}>;sqlite.close();expect(rows).toEqual([{uid:legacyNotice.uid,inline:1,external:0},{uid:modernNotice.uid,inline:0,external:1}]);expect(migrations.map(m=>m.version)).toEqual([1,2]);const legacySqlite=new Database(legacyDatabasePath,{readonly:true});expect(legacySqlite.query("SELECT COUNT(*) AS count FROM sqlite_schema WHERE name='schema_migrations'").get()).toEqual({count:0});legacySqlite.close();
  },60_000);
});

function push(path:string,hash:string,size:number){return{op:"push",path,relatedpath:null,extension:"bin",hash,ctime:1700000000000,mtime:1700000000100,folder:false,deleted:false,size,pieces:1};}
function init(token:string,vault:any,device:string,version:number,initial:boolean){return{op:"init",token,id:vault.id,keyhash:vault.keyhash,version,initial,device,encryption_version:3};}
async function initialize(probe:Probe,token:string,vault:any,device:string,version:number,initial:boolean){probe.json(init(token,vault,device,version,initial));expect(await probe.nextJson()).toMatchObject({res:"ok"});while((await probe.nextJson()).op!=="ready"){} }
async function post(port:number,path:string,body:Record<string,unknown>){return(await fetch(`http://127.0.0.1:${port}${path}`,{method:"POST",headers:{"content-type":"application/json",origin:"app://obsidian.md"},body:JSON.stringify(body)})).json();}
async function health(port:number,child:ReturnType<typeof Bun.spawn>){const deadline=Date.now()+30_000;while(Date.now()<deadline){if(child.exitCode!==null)throw new Error("server exited early");try{if((await fetch(`http://127.0.0.1:${port}/health`)).ok)return;}catch{}await Bun.sleep(50);}throw new Error("health timeout");}
async function freePort():Promise<number>{return new Promise((resolvePort,reject)=>{const server=createServer();server.once("error",reject);server.listen(0,"127.0.0.1",()=>{const address=server.address();if(!address||typeof address==="string")return reject(new Error("no port"));server.close(()=>resolvePort(address.port));});});}
class Probe{private queue:unknown[]=[];private waiters:Array<(v:unknown)=>void>=[];private constructor(readonly socket:WebSocket){socket.binaryType="arraybuffer";socket.addEventListener("message",e=>{const v=typeof e.data==="string"?JSON.parse(e.data):e.data;const waiter=this.waiters.shift();waiter?waiter(v):this.queue.push(v);});}static connect(url:string):Promise<Probe>{return new Promise((resolveProbe,reject)=>{const socket=new WebSocket(url,{headers:{Origin:"app://obsidian.md"}} as unknown as string[]);sockets.push(socket);const probe=new Probe(socket);socket.addEventListener("open",()=>resolveProbe(probe),{once:true});socket.addEventListener("error",()=>reject(new Error("websocket failed")),{once:true});});}json(v:Record<string,unknown>){this.socket.send(JSON.stringify(v));}async nextJson():Promise<any>{const v=await this.next();if(v instanceof ArrayBuffer)throw new Error("expected JSON");return v;}async nextBinary():Promise<ArrayBuffer>{const v=await this.next();if(!(v instanceof ArrayBuffer))throw new Error("expected binary");return v;}private next():Promise<unknown>{if(this.queue.length)return Promise.resolve(this.queue.shift());return new Promise((resolveValue,reject)=>{const timer=setTimeout(()=>reject(new Error("websocket timeout")),5000);this.waiters.push(v=>{clearTimeout(timer);resolveValue(v);});});}}
